export * from './as';
export * from './wx';
export * from './http';
export * from './httpConsole';
export * from './token';
export * from './cdn';
export * from './transfer';
export * from './search';
export * from './setWechatTitle';
export * from './miniprogram';
export * from './reg';
export { default as go } from './go';
